services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: runner
    env_file:
      - apps/api/.env
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: "0.0.0.0"
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:'+(process.env.PORT||3000)+'/healthz',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: runner
    env_file:
      - apps/web/.env
    environment:
      NODE_ENV: production
      PORT: "3001"
      # For browser calls:
      # NEXT_PUBLIC_API_BASE_URL: "http://localhost:3000"
    ports:
      - "3001:3001"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
