services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - apps/api/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - apps/web/.env
    ports:
      - "3001:3001"
    depends_on:
      - api
    restart: unless-stopped
